name: Playwright Tests

# Trigger the workflow on pushes and pull requests to the main branch.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    # Define the operating system to run the tests on.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'  # Adjust the Node.js version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Optional: Install Playwright browsers explicitly (if not auto-installed)
      - name: Install Playwright Browsers
        run: npx playwright install

      # Step 4: Build the TypeScript project (if you have a build step)
      - name: Build project
        run: npm run build

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: npm run loginTest

      # Step 6: Upload Test Artifacts (Optional: Useful for debugging test failures)
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/  # Ensure your tests generate a report at this path
